<?php

declare(strict_types=1);

use Jesperbeisner\Arbeitszeugnisgenerator\Stdlib\HtmlResponse;

/** @var HtmlResponse $this */

/** @var array<string, array<int, string>> $textsArray */
$textsArray = $this->get('textsArray');

?>
<header>
    <h1>
        <a href="https://github.com/jesperbeisner/arbeitszeugnisgenerator" title="Look at the source code of this application">
            Arbeitszeugnisgenerator
        </a>
    </h1>
</header>

<hr>

<main>
    <form method="POST" action="/download">
        <p>
            <label for="firstName">Vorname*</label>
            <input type="text" id="firstName" name="firstName" placeholder="Max" required>
        </p>

        <p>
            <label for="lastName">Nachname*</label>
            <input type="text" id="lastName" name="lastName" placeholder="Mustermann" required>
        </p>

        <p>
            <label for="leaveDate">Austrittsdatum*</label>
            <input type="date" id="leaveDate" name="leaveDate" required>
        </p>

        <fieldset>
            <legend>Geschlecht*</legend>
            <label>
                <input type="radio" name="gender" value="m" required>
                Männlich
            </label>
            <label>
                <input type="radio" name="gender" value="f" required>
                Weiblich
            </label>
        </fieldset>

        <?php foreach ($textsArray as $subject => $texts): ?>
            <fieldset>
                <legend><?= $subject ?></legend>

                <?php foreach ($texts as $grade => $text): ?>
                    <label>
                        <input type="radio" name="<?= strtolower(str_replace(' ', '_', $subject)) ?>" value="<?= $grade ?>">
                        <?= $grade ?>
                    </label>
                <?php endforeach; ?>
            </fieldset>
        <?php endforeach; ?>

        <p>
            <small>Felder, die mit einem Stern (*) gekennzeichnet sind, sind verpflichtend.</small>
        </p>

        <p>
            <button type="submit">Erstellen</button>
        </p>
    </form>
</main>
