<?php

declare(strict_types=1);

/** @var string $content */

?>
<!doctype html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link type="image/png" rel="icon" href="/img/favicon.png">
    <link type="text/css" rel="stylesheet" href="/css/main.css">
    <title>Arbeitszeugnisgenerator</title>
</head>
<body>
    <?= $content ?>
</body>
</html>
